[auth.cookie]
name = "st_auth"
key = "4d5b2c1f9c7a0a6e1b8e2f4c9a7d0e3f"
expiry_days = 30

[auth.credentials.usernames.pablo]
email = "pmorera@visioncoresystems.com"
name = "Pablo"
# password: VisionCore#2025
password = "$2b$12$08sbeU0dtIVyUGEFomDg3e.V9pGJN.WNM.F1aEhCR3bqtEN.aIo62"

[auth.credentials.usernames.jose]
email = "jose@alliedheavydutytowing.com"
name = "Jose"
# password: Allied#2025
password = "$2b$12$uDE8QltCVHMXTcvOj2xBRObWBSxP6ZBeMXef9aJ4KxlW6V9dlP6aS"
